version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server_db
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

  hm.api:
    image: ${DOCKER_REGISTRY-}hmapi
    build:
      context: .
      dockerfile: HM.API/Dockerfile
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=sa
      - DB_PASSWORD=YourStrong!Passw0rd
      - DB_NAME=HealthMed
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: /app

volumes:
  sqlserverdata: